var map = [
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ],
    [
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" },
        { tile: "ground", available: true, texture: "atlas", frame: "grid" }
    ]
];

exports.map = map;